# Generated by Django 4.1.3 on 2023-03-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("orders", models.JSONField()),
                ("email", models.CharField(max_length=64)),
                ("payment", models.IntegerField()),
                ("payment_method", models.CharField(max_length=64)),
                ("payment_id", models.CharField(max_length=64)),
                ("date_of_order", models.DateTimeField()),
            ],
        ),
    ]
